syntax = "proto3";
package google.api;

import "google/api/launch_stage.proto";
import "google/protobuf/duration.proto";

enum ClientLibraryOrganization {
  CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED = 0;
  CLOUD = 1;
  ADS = 2;
  PHOTOS = 3;
  STREET_VIEW = 4;
  SHOPPING = 5;
  GEO = 6;
  GENERATIVE_AI = 7;
}

enum ClientLibraryDestination {
  CLIENT_LIBRARY_DESTINATION_UNSPECIFIED = 0;
  GITHUB = 10;
  PACKAGE_MANAGER = 20;
}

message CommonLanguageSettings {
  string reference_docs_uri = 1;
  repeated google.api.ClientLibraryDestination destinations = 2;
  google.api.SelectiveGapicGeneration selective_gapic_generation = 3;
}

message ClientLibrarySettings {
  string version = 1;
  google.api.LaunchStage launch_stage = 2;
  bool rest_numeric_enums = 3;
  google.api.JavaSettings java_settings = 21;
  google.api.CppSettings cpp_settings = 22;
  google.api.PhpSettings php_settings = 23;
  google.api.PythonSettings python_settings = 24;
  google.api.NodeSettings node_settings = 25;
  google.api.DotnetSettings dotnet_settings = 26;
  google.api.RubySettings ruby_settings = 27;
  google.api.GoSettings go_settings = 28;
}

message Publishing {
  repeated google.api.MethodSettings method_settings = 2;
  string new_issue_uri = 101;
  string documentation_uri = 102;
  string api_short_name = 103;
  string github_label = 104;
  repeated string codeowner_github_teams = 105;
  string doc_tag_prefix = 106;
  google.api.ClientLibraryOrganization organization = 107;
  repeated google.api.ClientLibrarySettings library_settings = 109;
  string proto_reference_documentation_uri = 110;
  string rest_reference_documentation_uri = 111;
}

message JavaSettings {
  message ServiceClassNamesEntry {
    string key = 1;
    string value = 2;
  }

  string library_package = 1;
  repeated google.api.JavaSettings.ServiceClassNamesEntry service_class_names = 2;
  google.api.CommonLanguageSettings common = 3;
}

message CppSettings {
  google.api.CommonLanguageSettings common = 1;
}

message PhpSettings {
  google.api.CommonLanguageSettings common = 1;
}

message PythonSettings {
  message ExperimentalFeatures {
    bool rest_async_io_enabled = 1;
    bool protobuf_pythonic_types_enabled = 2;
    bool unversioned_package_disabled = 3;
  }

  google.api.CommonLanguageSettings common = 1;
  google.api.PythonSettings.ExperimentalFeatures experimental_features = 2;
}

message NodeSettings {
  google.api.CommonLanguageSettings common = 1;
}

message DotnetSettings {
  message RenamedServicesEntry {
    string key = 1;
    string value = 2;
  }

  message RenamedResourcesEntry {
    string key = 1;
    string value = 2;
  }

  google.api.CommonLanguageSettings common = 1;
  repeated google.api.DotnetSettings.RenamedServicesEntry renamed_services = 2;
  repeated google.api.DotnetSettings.RenamedResourcesEntry renamed_resources = 3;
  repeated string ignored_resources = 4;
  repeated string forced_namespace_aliases = 5;
  repeated string handwritten_signatures = 6;
}

message RubySettings {
  google.api.CommonLanguageSettings common = 1;
}

message GoSettings {
  message RenamedServicesEntry {
    string key = 1;
    string value = 2;
  }

  google.api.CommonLanguageSettings common = 1;
  repeated google.api.GoSettings.RenamedServicesEntry renamed_services = 2;
}

message MethodSettings {
  message LongRunning {
    google.protobuf.Duration initial_poll_delay = 1;
    float poll_delay_multiplier = 2;
    google.protobuf.Duration max_poll_delay = 3;
    google.protobuf.Duration total_poll_timeout = 4;
  }

  string selector = 1;
  google.api.MethodSettings.LongRunning long_running = 2;
  repeated string auto_populated_fields = 3;
}

message SelectiveGapicGeneration {
  repeated string methods = 1;
  bool generate_omitted_as_internal = 2;
}
