syntax = "proto3";
package google.internal.cloud.code.v1internal;

import "exa/api_server_pb/api_server.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

enum CascadeNuxLocation {
  CASCADE_NUX_LOCATION_UNSPECIFIED = 0;
  CASCADE_NUX_LOCATION_CASCADE_INPUT = 1;
  CASCADE_NUX_LOCATION_MODEL_SELECTOR = 2;
  CASCADE_NUX_LOCATION_RULES_TAB = 4;
  CASCADE_NUX_LOCATION_REVERT_STEP = 6;
  CASCADE_NUX_LOCATION_PLAN_MODE = 7;
  CASCADE_NUX_LOCATION_WRITE_CHAT_MODE = 8;
  CASCADE_NUX_LOCATION_TOOLBAR = 9;
  CASCADE_NUX_LOCATION_MANAGER_BOTTOM_LEFT = 10;
  CASCADE_NUX_LOCATION_ARTIFACT_VIEW_BOTTOM_LEFT = 11;
  CASCADE_NUX_LOCATION_CHAT_PANEL_BANNER = 12;
  CASCADE_NUX_LOCATION_ALWAYS_MOUNTED = 13;
}

enum CascadeNuxIcon {
  CASCADE_NUX_ICON_UNSPECIFIED = 0;
  CASCADE_NUX_ICON_WEB_SEARCH = 1;
  CASCADE_NUX_ICON_WINDSURF_BROWSER = 2;
}

enum CascadeNuxTrigger {
  CASCADE_NUX_TRIGGER_UNSPECIFIED = 0;
  CASCADE_NUX_TRIGGER_PRODUCED_CODE_DIFF = 1;
  CASCADE_NUX_TRIGGER_OPEN_BROWSER_URL = 3;
  CASCADE_NUX_TRIGGER_WEB_SEARCH = 4;
  CASCADE_NUX_TRIGGER_MANAGER_POSTONBOARDING_COMPLETE = 5;
  CASCADE_NUX_TRIGGER_MANAGER_ARTIFACT_CREATED = 6;
  CASCADE_NUX_TRIGGER_MANAGER_ARTIFACT_OPENED = 7;
  CASCADE_NUX_TRIGGER_MANAGER_FILE_OPENED = 8;
  CASCADE_NUX_TRIGGER_MANAGER_CONVERSATION_AVAILABLE = 10;
  CASCADE_NUX_TRIGGER_MANAGER_PROJECT_CREATED = 11;
  CASCADE_NUX_TRIGGER_MANAGER_PROJECT_ENVIRONMENT_SELECTION = 12;
  CASCADE_NUX_TRIGGER_MANAGER_CREATE_FIRST_PROJECT_DIALOG = 13;
}

enum NuxClient {
  NUX_CLIENT_UNSPECIFIED = 0;
  NUX_CLIENT_JETSKI = 1;
  NUX_CLIENT_ANTIGRAVITY = 2;
}

enum NUXInteractionType {
  NUX_INTERACTION_TYPE_UNSPECIFIED = 0;
  NUX_INTERACTION_TYPE_DISMISSED = 1;
  NUX_INTERACTION_TYPE_ACCEPTED = 2;
}

message SetUserSettingsRequest {
  google.internal.cloud.code.v1internal.UserSettings user_settings = 1;
}

message SetUserSettingsResponse {
  google.internal.cloud.code.v1internal.UserSettings user_settings = 1;
}

message UserSettings {
  bool telemetry_enabled = 1;
  bool user_data_collection_force_disabled = 2;
  bool marketing_emails_enabled = 3;
}

message FetchUserInfoRequest {
  string project = 1;
}

message FetchUserInfoResponse {
  google.internal.cloud.code.v1internal.UserSettings user_settings = 6;
  repeated string user_tags = 7;
  string region_code = 8;
}

message GetAgentPluginRequest {
  string name = 1;
}

message ListAgentPluginsRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
}

message ListAgentPluginsResponse {
  repeated google.internal.cloud.code.v1internal.AgentPlugin agent_plugins = 1;
  string next_page_token = 2;
}

message ListBuildWithGooglePluginsRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
}

message ListBuildWithGooglePluginsResponse {
  repeated google.internal.cloud.code.v1internal.BuildWithGooglePlugin build_with_google_plugins = 1;
  string next_page_token = 2;
}

message ListCascadeNuxesRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
}

message ListCascadeNuxesResponse {
  repeated google.internal.cloud.code.v1internal.CascadeNux cascade_nuxes = 1;
  string next_page_token = 2;
}

message ListWebDocsOptionsRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListWebDocsOptionsResponse {
  repeated google.internal.cloud.code.v1internal.WebDocsOption web_docs_options = 1;
  string next_page_token = 2;
}

message RewriteUriRequest {
  string original_uri = 1;
}

message RewriteUriResponse {
  string redirect_uri = 1;
}

message WebDocsOption {
  string label = 1;
  repeated string synonyms = 4;
  bool is_featured = 5;
  oneof value {
    string docs_uri = 2;
    string docs_search_domain = 3;
  }
}

message WebSearchRedirect {
  string search_domain = 1;
  repeated string redirect_paths = 2;
  string llms_full_txt_uri = 3;
  string llms_txt_uri = 4;
}

message AgentPlugin {
  string name = 1;
  string uid = 2;
  string link = 3;
  string description = 4;
  int64 installation_count = 6;
  string trust_level = 7;
  string readme = 8;
  oneof configuration {
    google.internal.cloud.code.v1internal.AgentPluginLocalConfig local = 9;
    google.internal.cloud.code.v1internal.AgentPluginRemoteConfig remote = 10;
  }
}

message GStaticSource {
  string link = 1;
}

message BuildWithGooglePlugin {
  message VersionShasEntry {
    string key = 1;
    string value = 2;
  }

  google.internal.cloud.code.v1internal.AgentPlugin plugin = 1;
  repeated google.internal.cloud.code.v1internal.BuildWithGooglePlugin.VersionShasEntry version_shas = 4;
  oneof source {
    google.internal.cloud.code.v1internal.GStaticSource gstatic = 3;
  }
}

message AgentPluginLocalConfig {
  message CommandsEntry {
    string key = 1;
    google.internal.cloud.code.v1internal.AgentPluginCommand value = 2;
  }

  repeated google.internal.cloud.code.v1internal.AgentPluginLocalConfig.CommandsEntry commands = 1;
}

message AgentPluginRemoteConfig {
  google.internal.cloud.code.v1internal.AgentPluginRemoteConfigTemplate remote_template = 2;
}

message AgentPluginRemoteConfigTemplate {
  message HeadersEntry {
    string key = 1;
    string value = 2;
  }

  string server_url = 1;
  repeated google.internal.cloud.code.v1internal.AgentPluginRemoteConfigTemplate.HeadersEntry headers = 2;
  string auth_provider_type = 3;
}

message AgentPluginCommand {
  google.internal.cloud.code.v1internal.AgentPluginCommandTemplate command_template = 1;
  repeated google.internal.cloud.code.v1internal.AgentPluginCommandVariable variables = 2;
}

message AgentPluginCommandTemplate {
  message EnvEntry {
    string key = 1;
    string value = 2;
  }

  string command = 1;
  repeated string args = 2;
  repeated google.internal.cloud.code.v1internal.AgentPluginCommandTemplate.EnvEntry env = 3;
}

message AgentPluginCommandVariable {
  string name = 1;
  string title = 2;
  string description = 3;
  string link = 4;
}

message CascadeNux {
  int32 uid = 1;
  google.internal.cloud.code.v1internal.CascadeNuxLocation location = 2;
  google.internal.cloud.code.v1internal.CascadeNuxTrigger trigger = 3;
  string analytics_event = 4;
  string learn_more_uri = 7;
  int32 priority = 8;
  google.internal.cloud.code.v1internal.CascadeNuxIcon icon = 10;
  bool requires_idle_cascade = 11;
  string title = 12;
  string body = 13;
  string image_url = 14;
  string video_url = 15;
  google.internal.cloud.code.v1internal.NuxFilter filter = 16;
  repeated google.internal.cloud.code.v1internal.NUXInteractionType available_interactions = 17;
  string learn_more_button_text = 18;
  string primary_cta_text = 19;
}

message NuxVersionFilter {
  string min_version = 1;
  string max_version = 2;
  repeated string exact_versions = 3;
}

message NuxFilter {
  repeated google.internal.cloud.code.v1internal.NuxClient clients = 1;
  google.internal.cloud.code.v1internal.NuxVersionFilter version_filter = 2;
  repeated string subclients = 3;
  repeated string user_tiers = 4;
}

message Interaction {
  oneof interaction_data {
    google.internal.cloud.code.v1internal.NUXInteraction nux_interaction = 1;
  }
}

message NUXInteraction {
  int32 nux_id = 1;
  google.internal.cloud.code.v1internal.NUXInteractionType interaction_type = 2;
}

message RegisterInteractionRequest {
  google.internal.cloud.code.v1internal.Interaction interaction = 1;
}

message RegisterInteractionResponse {
  string message = 1;
}

message TabChatRequest {
  string project = 1;
  exa.api_server_pb.GetChatMessageRequest request = 2;
}

message TabChatResponse {
  exa.api_server_pb.GetChatMessageResponse response = 1;
}

message CheckUrlDenylistRequest {
  string url = 1;
}

message CheckUrlDenylistResponse {
  bool is_denied = 1;
}

message GetHealthRequest {
  string name = 1;
}

message Health {
  string name = 1;
}

message RecordTrajectoryAnalyticsRequest {
  google.protobuf.Struct trajectory = 5;
  int32 start_step_index = 2;
  int32 start_generator_metadata_index = 3;
  google.protobuf.Struct metadata = 6;
  repeated int32 mendel_experiment_ids = 7;
}

message RecordTrajectoryAnalyticsResponse {
}

message FetchFromTrawlerCacheRequest {
  string url = 1;
  bool live_fetch = 2;
}

message FetchFromTrawlerCacheResponse {
  string content = 1;
}

message BattleModeOverridesRequest {
  repeated string model_ids = 1;
  bool auto_triggered = 2;
  string trigger_tag = 3;
}

message BattleModeOverridesResponse {
  bool should_override = 1;
  repeated string override_model_ids = 2;
}

message BattleModeAutoTriggerRequest {
  google.protobuf.Timestamp last_auto_trigger_request_time = 1;
  string model_id = 2;
}

message BattleModeAutoTriggerResponse {
  int32 target_battle_n = 1;
  string trigger_tag = 2;
}

service JetskiService {
  rpc ListAgentPlugins(google.internal.cloud.code.v1internal.ListAgentPluginsRequest) returns (google.internal.cloud.code.v1internal.ListAgentPluginsResponse);
  rpc ListBuildWithGooglePlugins(google.internal.cloud.code.v1internal.ListBuildWithGooglePluginsRequest) returns (google.internal.cloud.code.v1internal.ListBuildWithGooglePluginsResponse);
  rpc GetAgentPlugin(google.internal.cloud.code.v1internal.GetAgentPluginRequest) returns (google.internal.cloud.code.v1internal.AgentPlugin);
  rpc ListCascadeNuxes(google.internal.cloud.code.v1internal.ListCascadeNuxesRequest) returns (google.internal.cloud.code.v1internal.ListCascadeNuxesResponse);
  rpc ListWebDocsOptions(google.internal.cloud.code.v1internal.ListWebDocsOptionsRequest) returns (google.internal.cloud.code.v1internal.ListWebDocsOptionsResponse);
  rpc RewriteUri(google.internal.cloud.code.v1internal.RewriteUriRequest) returns (google.internal.cloud.code.v1internal.RewriteUriResponse);
  rpc FetchUserInfo(google.internal.cloud.code.v1internal.FetchUserInfoRequest) returns (google.internal.cloud.code.v1internal.FetchUserInfoResponse);
  rpc SetUserSettings(google.internal.cloud.code.v1internal.SetUserSettingsRequest) returns (google.internal.cloud.code.v1internal.SetUserSettingsResponse);
  rpc TabChat(google.internal.cloud.code.v1internal.TabChatRequest) returns (stream google.internal.cloud.code.v1internal.TabChatResponse);
  rpc CheckUrlDenylist(google.internal.cloud.code.v1internal.CheckUrlDenylistRequest) returns (google.internal.cloud.code.v1internal.CheckUrlDenylistResponse);
  rpc GetHealth(google.internal.cloud.code.v1internal.GetHealthRequest) returns (google.internal.cloud.code.v1internal.Health);
  rpc RecordTrajectoryAnalytics(google.internal.cloud.code.v1internal.RecordTrajectoryAnalyticsRequest) returns (google.internal.cloud.code.v1internal.RecordTrajectoryAnalyticsResponse);
  rpc FetchFromTrawlerCache(google.internal.cloud.code.v1internal.FetchFromTrawlerCacheRequest) returns (google.internal.cloud.code.v1internal.FetchFromTrawlerCacheResponse);
  rpc RegisterInteraction(google.internal.cloud.code.v1internal.RegisterInteractionRequest) returns (google.internal.cloud.code.v1internal.RegisterInteractionResponse);
  rpc BattleModeOverrides(google.internal.cloud.code.v1internal.BattleModeOverridesRequest) returns (google.internal.cloud.code.v1internal.BattleModeOverridesResponse);
  rpc BattleModeAutoTrigger(google.internal.cloud.code.v1internal.BattleModeAutoTriggerRequest) returns (google.internal.cloud.code.v1internal.BattleModeAutoTriggerResponse);
}
