syntax = "proto3";
package google.internal.cloud.code.v1internal;

import "exa/codeium_common_pb/codeium_common.proto";
import "google/protobuf/timestamp.proto";

message FetchAvailableModelsRequest {
  string project = 1;
  string request_id = 2;
}

message QuotaInfo {
  float remaining_fraction = 1;
  google.protobuf.Timestamp reset_time = 2;
}

message ModelDetails {
  message SupportedMimeTypesEntry {
    string key = 1;
    bool value = 2;
  }

  string display_name = 1;
  bool supports_images = 2;
  bool supports_thinking = 3;
  int32 thinking_budget = 4;
  int32 min_thinking_budget = 5;
  bool recommended = 6;
  int32 max_tokens = 7;
  int32 max_output_tokens = 8;
  string tokenizer_type = 9;
  google.internal.cloud.code.v1internal.QuotaInfo quota_info = 10;
  string beta_warning_message = 11;
  bool beta = 12;
  bool disabled = 13;
  string description = 14;
  exa.codeium_common_pb.Model model = 15;
  exa.codeium_common_pb.APIProvider api_provider = 16;
  exa.codeium_common_pb.ModelProvider model_provider = 17;
  bool supports_cumulative_context = 18;
  bool tab_jump_print_line_range = 19;
  bool supports_estimate_token_counter = 20;
  bool is_internal = 21;
  bool add_cursor_to_find_replace_target = 22;
  exa.codeium_common_pb.PromptTemplaterType prompt_templater_type = 23;
  exa.codeium_common_pb.ToolFormatterType tool_formatter_type = 24;
  bool supports_raw_thinking = 25;
  bool supports_video = 26;
  bool supports_pdf = 27;
  bool requires_lead_in_generation = 28;
  string tag_title = 29;
  string tag_description = 30;
  bool requires_no_xml_tool_examples = 31;
  repeated google.internal.cloud.code.v1internal.ModelDetails.SupportedMimeTypesEntry supported_mime_types = 32;
  bool requires_image_output_outside_function_responses = 33;
  bool preview = 34;
  int32 thinking_level = 35;
  string tool_response_key = 36;
  google.internal.cloud.code.v1internal.ModelExperiments model_experiments = 37;
  bool supports_thought_circulation = 38;
  string vertex_model_id = 39;
}

message ModelSort {
  string display_name = 1;
  repeated google.internal.cloud.code.v1internal.ModelGroup groups = 2;
}

message ModelGroup {
  string display_name = 1;
  repeated string model_ids = 2;
}

message DeprecatedModelReroutingInfo {
  string new_model_id = 1;
  exa.codeium_common_pb.Model old_model_enum = 2;
  exa.codeium_common_pb.Model new_model_enum = 3;
}

message ExperimentValue {
  oneof value {
    bool bool_value = 1;
    double float_value = 2;
    int64 int_value = 3;
    string string_value = 4;
  }
}

message ModelExperiments {
  message ExperimentsEntry {
    string key = 1;
    google.internal.cloud.code.v1internal.ExperimentValue value = 2;
  }

  repeated google.internal.cloud.code.v1internal.ModelExperiments.ExperimentsEntry experiments = 1;
}

message TieredModelConfig {
  repeated string flash_lite = 1;
  repeated string flash = 2;
  repeated string pro = 3;
}

message FetchAvailableModelsResponse {
  message ModelsEntry {
    string key = 1;
    google.internal.cloud.code.v1internal.ModelDetails value = 2;
  }

  message DeprecatedModelIdsEntry {
    string key = 1;
    google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfo value = 2;
  }

  repeated google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.ModelsEntry models = 1;
  string default_agent_model_id = 2;
  repeated google.internal.cloud.code.v1internal.ModelSort agent_model_sorts = 3;
  repeated string command_model_ids = 4;
  repeated string tab_model_ids = 5;
  repeated string image_generation_model_ids = 6;
  repeated string mquery_model_ids = 7;
  repeated string web_search_model_ids = 8;
  repeated string commit_message_model_ids = 10;
  repeated google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.DeprecatedModelIdsEntry deprecated_model_ids = 9;
  repeated string audio_transcription_model_ids = 11;
  repeated google.internal.cloud.code.v1internal.ModelSort battle_mode_model_sorts = 12;
  google.internal.cloud.code.v1internal.TieredModelConfig tiered_model_ids = 14;
  repeated int32 experiment_ids = 13;
}
